/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:851972c4-982b-4225-b75b-026cae2d0f1d',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_WvwYKuosP',
  aws_user_pools_web_client_id: '79spqv485fib34hmvcv6bhger5',
  oauth: {
    domain: 'parkyourself-auth-dev.auth.us-east-1.amazoncognito.com',
    scope: ['phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
    redirectSignIn: 'http://localhost:3000/,parkyourself://,https://d3fmot6d29rs7w.cloudfront.net/',
    redirectSignOut:
      'http://localhost:3000/,parkyourself://,https://d3fmot6d29rs7w.cloudfront.net/',
    responseType: 'code'
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_user_files_s3_bucket: 'parkyourself-content-bucket151403-dev',
  aws_user_files_s3_bucket_region: 'us-east-1',
  aws_mobile_analytics_app_id: 'c8f60bb963054bc8a8ceb2bda77acb67',
  aws_mobile_analytics_app_region: 'us-east-1',
  aws_appsync_graphqlEndpoint:
    ' https://hgrxc74qrreszclizfl52tuhsu.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-xl6bepawwzbt3igmharb4py5aa'
};

export default awsmobile;
