version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
  pre_build:
    commands:
      - echo Starting deployment
  build:
    commands:
      - serverless deploy --SERVICE_NAME $SERVICE_NAME --MONGO_USERNAME $MONGO_USERNAME --MONGO_PASSWORD $MONGO_PASSWORD
  post_build:
    commands:
      - echo Build completed on `date`