export const INITIALIZE_USER = 'INITIALIZE_USER';
export const LOAD_USER_TYPE = 'LOAD_USER_TYPE';
export const TOGGLE_USER_TYPE = 'TOGGLE_USER_TYPE';
export const TOGGLE_PROFILE_TYPE = 'TOGGLE_PROFILE_TYPE';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';

//ADD LISTING TYPES
export const ADD_LISTING_LOCATION = 'ADD_LISTING_LOCATION';
export const ADD_LISTING_SPACE_DETAILS = 'ADD_LISTING_SPACE_DETAILS';
export const ADD_LISTING_SPACE_AVAILABLE = 'ADD_LISTING_SPACE_AVAILABLE';
export const ADD_LISTING_PRICING_TYPE_AND_RATE =
  'ADD_LISTING_PRICING_TYPE_AND_RATE';
export const ADD_LISTING = 'ADD_LISTING';
export const CLEAR_LISTING = 'CLEAR_LISTING';
export const LOAD_USER_LISTINGS = 'LOAD_ALL_LISTINGS';
export const UPDATE_LISTING = 'UPDATE_LISTING';
export const PUBLISH_LISTING = 'PUBLISH_LISTING';
export const DELETE_LISTING = 'DELETE_LISTING';

//Find Parking
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';
export const CLEAR_SEARCH_DATA = 'CLEAR_SEARCH_DATA';

// Add Booking
export const ADD_BOOKING = 'ADD_BOOKING';
export const UPDATE_BOOKING = 'UPDATE_BOOKING';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const LOAD_USER_BOOKINGS = 'LOAD_USER_BOOKINGS';

//Add Vehicle
export const LOAD_USER_VEHICLES = 'LOAD_USER_VEHICLES';
export const ADD_VEHICLE = 'ADD_VEHICLE';
export const UPDATE_VEHICLE = 'UPDATE_VEHICLE';
export const DELETE_VEHICLE = 'DELETE_VEHICLE';

// Load Business Profile
export const LOAD_USER_BUSINESS_PROFILE = 'LOAD_USER_BUSINESS_PROFILE';
export const CREATE_BUSINESS_PROFILE = 'CREATE_BUSINESS_PROFILE';
export const UPDATE_BUSINESS_PROFILE = 'UPDATE_BUSINESS_PROFILE';
export const DELETE_BUSINESS_PROFILE = 'DELETE_BUSINESS_PROFILE';

// Load Space Owner Profile
export const LOAD_USER_SPACEOWNER_PROFILE = 'LOAD_USER_SPACEOWNER_PROFILE';
export const CREATE_SPACEOWNER_PROFILE = 'CREATE_SPACEOWNER_PROFILE';
export const UPDATE_SPACEOWNER_PROFILE = 'UPDATE_SPACEOWNER_PROFILE';
export const DELETE_SPACEOWNER_PROFILE = 'DELETE_SPACEOWNER_PROFILE';

// Listing Review
export const LOAD_LISTING_REVIEWS = 'LOAD_LISTING_REVIEWS';
export const CREATE_LISTING_REVIEW = 'CREATE_LISTING_REVIEW';
export const UPDATE_LISTING_REVIEW = 'UPDATE_LISTING_REVIEW';
export const DELETE_LISTING_REVIEW = 'DELETE_LISTING_REVIEW';
