export const TOGGLE_USER_TYPE = 'TOGGLE_USER_TYPE';

//ADD LISTING TYPES
export const ADD_LISTING_LOCATION = 'ADD_LISTING_LOCATION';
export const ADD_LISTING_SPACE_DETAILS = 'ADD_LISTING_SPACE_DETAILS';
export const ADD_LISTING_SPACE_AVAILABLE = 'ADD_LISTING_SPACE_AVAILABLE';
export const SET_LISTING_PRICING_TYPE_AND_RATE =
  'SET_LISTING_PRICING_TYPE_AND_RATE';
export const ADD_LISTING = 'ADD_LISTING';
export const CLEAR_LISTING = 'CLEAR_LISTING';
export const ADD_VEHICLE = 'ADD_VEHICLE';
export const DELETE_VEHICLE = 'DELETE_VEHICLE';

//ADD BOOKING TYPES
export const ADD_BOOKING = 'ADD_BOOKING';
// export const ADD_TIMING = 'ADD_TIMING';
// export const UPDATE_TIMING = 'UPDATE_TIMING';
// export const ADD_VEHICLE  = "ADD_VEHICLE";
// export const UPDATE_VEHICLE  = "UPDATE_VEHICLE";
// export const ADD_CREDIT_DEBIT_CARD  = "ADD_CREDIT_DEBIT_CARD";
